### ISSUE TITLE
Got SIGTERM, shutting down Homebridge...

### ISSUE THREAD

**Issue by Kermarc44** [dubocr/homebridge-tahoma#103]
Bonjour,

J'ai un bug depuis hier.
Je pense que c'est depuis que j'ai fait la mise à jour de HomeBridge et du plugin Tahoma : 

[6/6/2019, 6:05:09 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[6/6/2019, 6:05:10 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[6/6/2019, 6:05:10 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[6/6/2019, 6:05:10 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by dubocr** [comment]
J'ai fait la mise à jour d'homebridge mais ne constate pas ce problème. Pouvez-vous désactiver le plugin tahoma pour vérifier d'où vient le problème.

Merci.

**Comment by Kermarc44** [comment]
J'ai réinstallé homebridge sans le plugin et j'ai l'erreur dès que j'essaie d'ajouter homebridge dans l'application maison.
Le problème ne vient donc pas du plugin mais de homebridge ou de l'application maison.
Le message que j'ai est cependant plus court :

[6/13/2019, 7:55:16 PM] Homebridge is running on port 38581.
[6/13/2019, 7:56:09 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
[6/13/2019, 7:56:09 PM] Got SIGTERM, shutting down Homebridge...

**Comment by Kermarc44** [comment]
Bonjour,

J'ai enfin pris le temps de me pencher sur le sujet.
Le problème venait de node js.
J'étais en version 6.17.1. Je suis passé en version 10.16.3 et ça a réglé le problème.

Marc
