### ISSUE TITLE
Problème récepteur RTS 

### ISSUE THREAD

**Issue by koupus** [dubocr/homebridge-tahoma#104]
Bonjour Romain,
j'ai un récepteur RTS qui ne fonctionne plus via Homekit et qui fait redémarrer Homebridge a chaque tentative d'utilisation. Je pense à la dernière MAJ du plugin mais sans certitude.
Ci dessous le log après action...
Une idée ?

D'avance merci, Thomas

[6/10/2019, 2:41:03 PM] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 5000
    at setTimeout (timers.js:118:11)
    at GarageDoorOpener.setState (/usr/local/lib/node_modules/homebridge-tahoma/services/GarageDoorOpener.js:38:17)
    at Characteristic.TargetDoorState.emit (events.js:200:13)
    at Characteristic.TargetDoorState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:200:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:200:13)
    at endReadableNT (_stream_readable.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[6/10/2019, 2:41:03 PM] Got SIGTERM, shutting down Homebridge...

**Comment by dubocr** [comment]
Bonjour,

Cela devrait être corrigé dans la dernière mise à jour.

**Comment by koupus** [comment]
Bonjour Romain,

problème réglé avec la dernière mis à jour.

Merci
