### ISSUE TITLE
Action Garage fait planter homebridge

### ISSUE THREAD

**Issue by nanoupi42** [dubocr/homebridge-tahoma#105]
Bonjour :-)

Pour info, j'ai constaté que lorsque j'ouvre ou ferme mon garage, HomeBridge plante :

[6/12/2019, 9:06:24 PM] [Tahoma] Update core:NameState => alarm name
[6/12/2019, 9:06:24 PM] [Tahoma] Update internal:CurrentAlarmModeState => off
[6/12/2019, 9:06:24 PM] [Tahoma] Update internal:AlarmDelayState => 60
[6/12/2019, 9:06:24 PM] [Tahoma] Update internal:TargetAlarmModeState => off
[6/12/2019, 9:06:24 PM] [Tahoma] Update internal:IntrusionDetectedState => notDetected
[6/12/2019, 9:07:49 PM] [Tahoma] [Garage] cycle[]
[6/12/2019, 9:07:54 PM] TypeError: this.currentState.update is not a function
    at GarageDoorOpener.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/services/GarageDoorOpener.js:39:36)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Je suis en dernière version. 

Morgane

**Comment by dubocr** [comment]
Bonjour,

Effectivement, je viens de mettre à jour le plugin avec un correctif. Cela devrait corriger le problème en mettant à jour.

Merci pour ce retour.

**Comment by nanoupi42** [comment]
Bonjour,
Yes c'est parfait c'est corrigé ! Merci pour la correction ! :-)
