### ISSUE TITLE
Error: The requested platform 'connexoon' was not registered by any plugin.

### ISSUE THREAD

**Issue by vrucht** [dubocr/homebridge-tahoma#113]
Hello, I followed the install instructions for the plugin and edited the json file. But in de log of the Homebridge i see the following error text:

[7/5/2019, 11:08:19 PM] Loaded config.json with 0 accessories and 3 platforms.
[7/5/2019, 11:08:19 PM] ---
[7/5/2019, 11:08:19 PM] Loaded plugin: homebridge-dummy
[7/5/2019, 11:08:19 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[7/5/2019, 11:08:19 PM] ---
[7/5/2019, 11:08:19 PM] Loaded plugin: homebridge-ikea-tradfri-gateway
[7/5/2019, 11:08:19 PM] Registering platform 'homebridge-ikea-gateway.Ikea Trådfri Gateway'
[7/5/2019, 11:08:19 PM] ---
[7/5/2019, 11:08:20 PM] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.4
[7/5/2019, 11:08:20 PM] Registering platform 'homebridge-tahoma.Tahoma'
[7/5/2019, 11:08:20 PM] ---
[7/5/2019, 11:08:20 PM] Loaded plugin: homebridge-config-ui-x
[7/5/2019, 11:08:20 PM] Registering platform 'homebridge-config-ui-x.config'
[7/5/2019, 11:08:20 PM] ---
[7/5/2019, 11:08:20 PM] Loading 3 platforms...
[7/5/2019, 11:08:20 PM] **Error: The requested platform 'connexoon' was not registered by any plugin.**
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

I have double checked everything but cannot find what is wrong. With my credentials filled in the form to test the connection to somfy, and that works. Can someone please give me a hand?
My json config:

        {
            "platform": "connexoon",
            "name": "connexoon",
            "user": "xxxxx@gmail.com",
            "password": "xxxxxxx"
        },

Thanks in advance.
regards,
Marc

**Comment by vrucht** [comment]
Fixed it:

The "platform" should say: "homebridge-tahoma.Tahoma" instead of "Thahoma" as the example

**Comment by dubocr** [comment]
Hi Marc,
This is a homebridge error. Until platform is defined to "Tahoma" this plugin is not activated so nothing is related to it. I'll try to improve readme to avoid mistakes.

Thanks for your feedback.
