### ISSUE TITLE
Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by chicochaleur29** [dubocr/homebridge-tahoma#116]
Bonjour
J'ai cette erreur qui apparait aujourd'hui (avant tout allait bien) et cela me fait rebooter homebridge ensuite

[7/31/2019, 10:21:15 PM] TypeError: Cannot read property 'debug' of undefined
    at Timeout.requestWithLogin [as _onTimeout] (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:228:22)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

[7/31/2019, 10:21:15 PM] Got SIGTERM, shutting down Homebridge...

Possible de voir?

Merci
Cordialement

**Comment by chicochaleur29** [comment]
R.A.S aujourd'hui
