### ISSUE TITLE
Problème sur déclenchement Camera Outdoor Somfy (myfox)

### ISSUE THREAD

**Issue by koupus** [dubocr/homebridge-tahoma#129]
Bonsoir Romain,

le déclenchement du capteur de mouvement de ma camera extérieur Somfy Outdoor semble provoquer une erreur (dont tu trouveras le lot ci dessous) qui entraine le redémarrage d'Homebridge...
Je viens de me loguer sur ton dev si cela peut aider.
Une idée? Voir correction ?

++ Thomas

le log:
[11/19/2019, 5:57:29 PM] ReferenceError: currentState is not defined
    at OccupancySensor.onStateUpdate (/usr/local/lib/node_modules/homebridge-tahoma/services/OccupancySensor.js:32:20)
    at OverkizDevice.onStatesUpdate (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-device.js:93:22)
    at TahomaPlatform.onStatesChange (/usr/local/lib/node_modules/homebridge-tahoma/index.js:222:12)
    at pollingtoevent.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:104:52)
    at pollingtoevent.emit (events.js:200:13)
    at done (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/polling-to-event/index.js:63:20)
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:90:14
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:223:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[11/19/2019, 5:57:29 PM] Got SIGTERM, shutting down Homebridge...

**Comment by dubocr** [comment]
Bonjour Thomas,

Merci pour ton retour.
J'ai corrigé le code cela devrait corrigé le problème avec une mise à jour du plugin.

Bonne journée.
