### ISSUE TITLE
Homebridge crash when setting heat pump params

### ISSUE THREAD

**Issue by ag0r4n** [dubocr/homebridge-tahoma#178]
```
[6/1/2020, 11:14:18 PM] [Tahoma] FROM 0/16 TO 0/5
[6/1/2020, 11:14:18 PM] [Tahoma] [Clim Nuit] globalControl["off",5,"auto","auto","manu"]
[6/1/2020, 11:14:20 PM] [Tahoma] FROM 0/16 TO 2/25
[6/1/2020, 11:14:20 PM] [Tahoma] [Clim Nuit] globalControl["on",25,"auto","cooling","manu"]
[6/1/2020, 11:14:23 PM] [Tahoma] [Clim Nuit] globalControl ACTUATORNOANSWER
[6/1/2020, 11:14:23 PM] [Tahoma] Callback already triggered
[6/1/2020, 11:14:23 PM] TypeError: Cannot read property 'SERVICE_COMMUNICATION_FAILURE' of undefined
    at Thermostat.<anonymous> (/homebridge/node_modules/homebridge-tahoma/services/Thermostat.js:430:62)
    at OverkizDevice.<anonymous> (/homebridge/node_modules/homebridge-tahoma/overkiz-device.js:165:4)
    at Queue.callback (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:35:33)
    at pollingtoevent.<anonymous> (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:168:21)
    at pollingtoevent.emit (events.js:315:20)
    at done (/homebridge/node_modules/homebridge-tahoma/node_modules/polling-to-event/index.js:63:20)
    at /homebridge/node_modules/homebridge-tahoma/overkiz-api.js:142:14
    at Request.authCallback [as _callback] (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:294:17)
    at Request.self.callback (/homebridge/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
[6/1/2020, 11:14:23 PM] Got SIGTERM, shutting down Homebridge...
[6/1/2020, 11:14:27 PM] [Tahoma] [Clim Nuit] globalControl ACTUATORNOANSWER
[6/1/2020, 11:14:27 PM] [Tahoma] Callback already triggered
[6/1/2020, 11:14:27 PM] TypeError: Cannot read property 'SERVICE_COMMUNICATION_FAILURE' of undefined
    at Thermostat.<anonymous> (/homebridge/node_modules/homebridge-tahoma/services/Thermostat.js:430:62)
    at OverkizDevice.<anonymous> (/homebridge/node_modules/homebridge-tahoma/overkiz-device.js:165:4)
    at Queue.callback (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:35:33)
    at pollingtoevent.<anonymous> (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:168:21)
    at pollingtoevent.emit (events.js:315:20)
    at done (/homebridge/node_modules/homebridge-tahoma/node_modules/polling-to-event/index.js:63:20)
    at /homebridge/node_modules/homebridge-tahoma/overkiz-api.js:142:14
    at Request.authCallback [as _callback] (/homebridge/node_modules/homebridge-tahoma/overkiz-api.js:294:17)
    at Request.self.callback (/homebridge/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
[6/1/2020, 11:14:28 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/1/2020, 11:14:33 PM] [HB Supervisor] Restarting Homebridge...
[6/1/2020, 11:14:33 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[6/1/2020, 11:14:33 PM] [HB Supervisor] Started Homebridge v1.1.0 with PID: 5279
[6/1/2020, 11:14:34 PM] Loaded config.json with 0 accessories and 7 platforms.
```

NodeJS  v12.17.0 
NPM  v6.14.4 
Homebridge 1.1.0
Homebridge-tahoma v0.3.35

**Comment by dubocr** [comment]
Hi,

it seem your bridge fail to communicate with your heat pump. Can you try with Cozytouch app then try again with Home app and then log to https://dev.duboc.pro/tahoma and give me your SETUP-XXXX-XXXX-XXXX number that appears.

Thanks

**Comment by firefighter79** [comment]
Hi,
here the same - when changing the temperature of my Danfoss Living Connect e.g. "Wohnzimmer" in Apple Home App, the Homebridge crashes and performs a restart.

Log:
[6/21/2020, 00:28:31] [My Tahoma] No target command for Wohnzimmer
[6/21/2020, 00:28:31] TypeError: Cannot read property 'SERVICE_COMMUNICATION_FAILURE' of undefined
    at Thermostat.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/services/Thermostat.js:430:62)
    at OverkizDevice.executeCommand (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-device.js:112:4)
    at Thermostat.setTargetState (/usr/local/lib/node_modules/homebridge-tahoma/services/Thermostat.js:417:15)
    at TargetHeatingCoolingState.emit (events.js:310:20)
    at TargetHeatingCoolingState.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at TargetHeatingCoolingState.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:625:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
    at HAPServer.emit (events.js:310:20)
[6/21/2020, 00:28:31] Got SIGTERM, shutting down Homebridge...
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service RestartSec=10s expired, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 2.
Stopped Node.js HomeKit Server.

Any ideas?

**Comment by dubocr** [comment]
Hi, You could try with latest version, must be OK

**Comment by ag0r4n** [comment]
I can confirm that the bug is not present on the last version ! Thank you @dubocr
