### ISSUE TITLE
Homebridge crash since version 0.3.41 - Opening / Close awning

### ISSUE THREAD

**Issue by BigKrisch** [dubocr/homebridge-tahoma#185]
Hello,

since version 0.3.41 the Homebridge always crashes with the following error message when opening or closing the awning:
With version 0.3.40 it works without problems.

> [2020-6-24 13:50:02] [Tahoma] Initializing Tahoma platform...
[2020-6-24 13:50:02] [Tahoma] Fetch accessories...
[2020-6-24 13:50:02] [Tahoma] Login TaHoma server...
[2020-6-24 13:50:02] [Tahoma] Unable to refresh states (not logged in)
[2020-6-24 13:50:03] [Tahoma] [Alarm] type: Alarm > TSKAlarmController, protocol: internal
[2020-6-24 13:50:03] [Tahoma] Device Alarm ignored
[2020-6-24 13:50:03] [Tahoma] [Sensitive Taste] type: Pod > Pod, protocol: internal
[2020-6-24 13:50:03] [Tahoma] No definition found for Pod > Pod in mapping.json file
[2020-6-24 13:50:03] [Tahoma] [Markise] type: Awning > UpDownHorizontalAwning, protocol: rts
[2020-6-24 13:50:03] [Tahoma] Instanciate Markise as WindowCovering
[2020-6-24 13:50:03] [Tahoma] [Markise Eltern] type: Awning > UpDownHorizontalAwning, protocol: rts
[2020-6-24 13:50:03] [Tahoma] Instanciate Markise Eltern as WindowCovering
[2020-6-24 13:50:03] Initializing platform accessory 'Markise OG'...
[2020-6-24 13:50:03] Initializing platform accessory 'Markise'...
Setup Payload:
X-HM://0023SYYC2JE9P
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:                  
[2020-6-24 13:50:03] Homebridge is running on port 12345.
_**[2020-6-24 13:50:23] TypeError: Cannot read property 'value' of undefined
    at WindowCovering.setTarget (/usr/local/lib/node_modules/homebridge-tahoma/services/WindowCovering.js:50:79)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-device.js:196:10)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)**_
[2020-6-24 13:50:23] Got SIGTERM, shutting down Homebridge...`

**Comment by mahuch** [comment]
crash since version 0.3.41 

[2020-6-24 14:19:22] TypeError: Cannot read property 'value' of undefined
    at WindowCovering.setTarget (/usr/local/lib/node_modules/homebridge-tahoma/services/WindowCovering.js:50:79)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-device.js:196:10)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by dubocr** [comment]
Fix in latests releases
