### ISSUE TITLE
Another problem after update

### ISSUE THREAD

**Issue by henkied** [dubocr/homebridge-tahoma#258]
see below, i have de install and install again with version 2.1.3

[3/22/2021, 8:18:32 PM] [TaHoma(test)] Map device Garagedeur
[3/22/2021, 8:18:32 PM] [TaHoma(test)] TypeError: this.targetState.onSet is not a function
    at GarageDoor.registerServices (/homebridge/node_modules/homebridge-tahoma/src/mappers/GarageDoor.ts:24:26)
    at new Mapper (/homebridge/node_modules/homebridge-tahoma/src/Mapper.ts:38:14)
    at new GarageDoor (/homebridge/node_modules/homebridge-tahoma/src/mappers/GarageDoor.ts:6:1)
    at Platform.discoverDevices (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:114:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[3/22/2021, 8:18:32 PM] [TaHoma(test)] Retry in 60 sec...
[3/22/2021, 8

**Comment by dubocr** [comment]
Hi,

You should update homebridge version to latest one. Don't know why homebridge don't tel you that.
