### ISSUE TITLE
user and password

### ISSUE THREAD

**Issue by Scream4Life** [dubocr/homebridge-tahoma#3]
Do you enter the username with @ symbol (email address)? And you put the whole thing in "[ ]" to make it work? I get an "Unable to login: Error: getaddrinfo ENOTFOUND undefined undefined:443" error when loading homebrige.

**Comment by dubocr** [comment]
Hi,

You have to set the username as in your TaHoma app. So if it's an email address yes put the full address inside quotes like "user" : "email@provider.com". You don't have to put brackets.
"getaddrinfo ENOTFOUND" seem to be a DNS error, please check "service" : "TaHoma" or remove it completely to leave default value.

**Comment by Scream4Life** [comment]
Thanks for your quick response. But when I do it that way I get this error while loading

/usr/local/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:89
        for (state of this.device.states) {
                                 ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at AbstractAccessory._look_state (/usr/local/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:89:34)
    at AbstractAccessory (/usr/local/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:41:26)
    at new RollerShutter (/usr/local/lib/node_modules/homebridge-tahoma/accessories/RollerShutter.js:19:23)
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:56:35
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:177:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)


I added this platform
 {
                "platform": "Tahoma",
                "name": "Tahoma",
                "user": "name@domain.de",
                "password": "PW1234"
            },

**Comment by dubocr** [comment]
OK, connexion succeed if you encountered this kind of error. Can you please log with your credentials at http://home.dubocr.fr/tools/setup to check your configuration and try to reproduce this issue. In the same time, if you are familiar you can try to add the following line at line 89 of _/usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js_ file :
`if(this.device != null)`

**Comment by dubocr** [comment]
This realize wasn't tested with non-acknowledgeable device like your RTS roller shutter.
Adding the following line at line 89 of _/usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js_ file might fix the issue :
`if(this.device.states != null)`

**Comment by Scream4Life** [comment]
within node_modules/ I only find the npm folder

**Comment by dubocr** [comment]
I've updated the npm package. You can try un update `npm update -g tahoma-plugin`.

**Comment by Scream4Life** [comment]
now the error while loading is this

/usr/local/lib/node_modules/homebridge-tahoma/accessories/RollerShutter.js:24
    this.targetPosition.on('set', this.setPosition.bind(this));
                                                  ^

TypeError: Cannot read property 'bind' of undefined
    at new RollerShutter (/usr/local/lib/node_modules/homebridge-tahoma/accessories/RollerShutter.js:24:51)
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:52:35
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:173:4
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:196:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)

First I did your update command without any effect. Than I did the install again.

**Comment by dubocr** [comment]
Don't see what's wrong here. Could be possible to access your raspberry remotely to debug ?

**Comment by Scream4Life** [comment]
Not today...but How?




Am 23.02.2017 um 20:54 schrieb Romain DUBOC <notifications@github.com>:

Don't see what's wrong here. Could be possible to access your raspberry remotely to debug ?

**Comment by dubocr** [comment]
Contact me by mail when you will be available to test. You will have to open port on your router.

You can try to add following lines in _/usr/local/lib/node_modules/homebridge-tahoma/accessories/RollerShutter.js_

After line 23 :
```
log("targetPosition " + this.targetPosition);
log("setPosition " + this.setPosition);
log("onStateUpdate " + this.onStateUpdate);
log("UUID " + this.UUID);
```

And send me your console log.

**Comment by Scream4Life** [comment]
Found the line, and this is the log

[2017-02-23 23:33:15] [Tahoma] targetPosition [object Object]
[2017-02-23 23:33:15] [Tahoma] setPosition undefined
[2017-02-23 23:33:15] [Tahoma] onStateUpdate function (name, value) {
        /**
        *	Track here update of any state for this accessory
        *	You might then update corresponding Homekit Characteristic as follow :
        *	this.service.getCharacteristic(Characteristic.TargetPosition).updateValue(value);
        **/
    }
[2017-02-23 23:33:15] [Tahoma] UUID undefined
/usr/local/lib/node_modules/homebridge-tahoma/accessories/RollerShutter.js:30
    this.targetPosition.on('set', this.setPosition.bind(this));
                                                  ^

TypeError: Cannot read property 'bind' of undefined
    at new RollerShutter (/usr/local/lib/node_modules/homebridge-tahoma/accessories/RollerShutter.js:30:51)
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:52:35
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:173:4
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:196:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)

**Comment by dubocr** [comment]
You can try this
```
cd /usr/local/lib/node_modules/homebridge-tahoma
npm uninstall util
npm install util
npm uninstall inherit
npm install inherit
```

**Comment by Scream4Life** [comment]
same message when i start homebridge. note that the log commands are still in the rollershutter.js. and by the way...you are awesome. your willingness to help me with this commendable.

**Comment by Scream4Life** [comment]
The port forwarding thing might be a bit problematic at this time. What about a teamviewer session? I've some time right now if possible for you.

**Comment by dubocr** [comment]
Ok for a teamviewer. You can send me credential by mail : wab@dubocr.fr

**Comment by dubocr** [comment]
Fixed be removing 'util' dependancy.
