### ISSUE TITLE
 TypeError: this.prog.onSet is not a function

### ISSUE THREAD

**Issue by ThomasPoiree** [dubocr/homebridge-tahoma#313]
I'm getting the error  TypeError: this.prog.onSet is not a function in the logs of homebridge since I updated.

**Comment by ThomasPoiree** [comment]
Complete logs : 

TypeError: this.prog.onSet is not a function
    at AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint.registerThermostatService (/usr/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem.ts:57:23)
    at AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint.registerServices (/usr/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem/AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint.ts:18:14)
    at AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint.build (/usr/lib/node_modules/homebridge-tahoma/src/Mapper.ts:51:14)
    at Platform.discoverDevices (/usr/lib/node_modules/homebridge-tahoma/src/Platform.ts:132:53)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by dubocr** [comment]
Hi,

What is your homebridge version ? You could try to update homebridge.
