### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#356]
Bonjour Romain,
J'ai eu cette erreur qui a fait rebooter Homebridge :
`[37m[1/16/2022, 7:02:01 PM] [39m[31mTypeError: Cannot read properties of null (reading 'failureType')[39m
[31m    at Execution.onStateUpdate (/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/models/Execution.ts:54:19)[39m
[31m    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:212:31)[39m
[31m    at listOnTimeout (node:internal/timers:557:17)[39m
[31m    at processTimers (node:internal/timers:500:7)[39m
[37m[1/16/2022, 7:02:01 PM] [39mGot SIGTERM, shutting down Homebridge...
[37m[1/16/2022, 7:02:06 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null
[37m[1/16/2022, 7:02:11 PM][0m [36m[HB Supervisor][0m Restarting Homebridge...`

**Comment by Dreiviertelblut** [comment]
dito: Server on Somfy side lacks perfomance recently, as I see it. Nevertheless, as blinds move into end position, the error handling of the addin is the main concern. It kills Homebridge service. 

[19.1.2022, 16:47:51] [Tahoma] [Schlafzimmer] close[]
[19.1.2022, 16:47:51] [Tahoma] [Ankleide] close[]
[19.1.2022, 16:48:52] [Tahoma] [Gaube links klein] close[]
[19.1.2022, 16:48:52] [Tahoma] [Gaube mitte] close[]
[19.1.2022, 16:48:52] [Tahoma] [Gaube rechts klein] close[]
[19.1.2022, 16:48:52] [Tahoma] [Gaube rechts] close[]
[19.1.2022, 16:49:09] [Tahoma] [Schlafzimmer] close COMPLETED
[19.1.2022, 16:49:29] [Tahoma] [Ankleide] close COMPLETED
[19.1.2022, 16:50:19] [Tahoma] [Gaube links klein] close COMPLETED
[19.1.2022, 16:50:24] [Tahoma] [Gaube mitte] close COMPLETED
[19.1.2022, 16:50:49] [Tahoma] [Gaube rechts klein] close COMPLETED
[19.1.2022, 16:50:53] TypeError: Cannot read properties of null (reading 'failureType')
    at Execution.onStateUpdate (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/models/Execution.ts:54:19)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:212:31)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[19.1.2022, 16:50:53] Got SIGTERM, shutting down Homebridge...
[19.1.2022, 16:50:54] [Tahoma] [Gaube rechts] close COMPLETED
[19.1.2022, 16:50:58] [Hue] goodbye
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service RestartSec=10s expired, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 1.
Stopped Node.js HomeKit Server.
Started Node.js HomeKit Server.

**Comment by dubocr** [comment]
Hi,

Error should be fixed since winter. Homebridge restart in case of uncaught error is fixed in latest releases.

Tes
