### ISSUE TITLE
Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)

### ISSUE THREAD

**Issue by byna** [dubocr/homebridge-tahoma#386]
Hi!

I constantly get authentication errors when polling. It seems to work the first time after restarting Homebridge but after that I always get the following error message:
[07/09/2022, 14:16:58] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)

Do you have any idea how to fix/get around it?

Thanks for your great work with the plugin 👍

**Comment by dubocr** [comment]
Hi,

Can you send me more log to check the complete sequence (with login, register, fetch, ...).
Do you change config params like pollingPeriod ?
What is your plugin version ?

Thank you.

**Comment by barthoefs** [comment]
Same issue here since updating today.

```
[9/7/2022, 5:46:28 PM] [Connexoon] API client will be locked for 60 seconds because of bad credentials or temporary service outage. You can restart plugin to force login retry (not recommanded except if you think your credentials are wrong).
[9/7/2022, 5:46:28 PM] [Connexoon] Error 401 Bad credentials (AUTHENTICATION_ERROR)
[9/7/2022, 5:46:28 PM] TypeError: this.log is not a function
    at process.error (/homebridge/node_modules/homebridge/src/logger.ts:139:10)
    at process.emit (node:events:513:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
/homebridge/node_modules/homebridge/lib/logger.js:90
        this.log("error" /* ERROR */, message, ...parameters);
             ^

TypeError: this.log is not a function
    at process.error (/homebridge/node_modules/homebridge/src/logger.ts:139:10)
    at process.emit (node:events:525:35)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
    at process._fatalException (node:internal/process/execution:167:25)
```

homebridge-tahoma v2.2.31

**Comment by byna** [comment]
Plugin version: v2.2.30
My password is also working on the  somfy website and in the app 

[07/09/2022, 14:38:49] [TaHoma] Initializing Tahoma platform...
[07/09/2022, 14:38:49] [WeatherPlus] Initializing WeatherPlus platform...
[07/09/2022, 14:38:49] [WeatherPlus] Adding station with weather service OpenWeatherMap named 'Weather station plus'
[07/09/2022, 14:38:49] Initializing platform accessory 'Weather station plus'...
[07/09/2022, 14:38:49] Initializing platform accessory 'Pergola'...

and then

[07/09/2022, 14:38:50] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge F9B4) is running on port 51962.
[07/09/2022, 14:38:50] [Broadlink RM] [INFO] Discovered Manual RM4 Pro Device (2227) at 192.168.86.186 (24:df:a7:f1:16:49)
[07/09/2022, 14:38:51] [TaHoma] Configure device Solsensor
[07/09/2022, 14:38:51] [TaHoma]   LightSensor > LuminanceSensor
[07/09/2022, 17:05:32] [TaHoma] Polling error - connect ENETUNREACH 178.32.15.131:443
[07/09/2022, 17:46:33] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[07/09/2022, 17:46:33] [TaHoma] API client will be locked for 60 seconds because of bad credentials or temporary service outage. You can restart plugin to force login retry (not recommanded except if you think your credentials are wrong).
[07/09/2022, 17:46:33] [TaHoma] Registration error - Error 401 Bad credentials (AUTHENTICATION_ERROR)

**Comment by DaniS81** [comment]
Same issue since the update... installation of an old version didn't solve the issue...

Does anyone has a solution?

**Comment by barthoefs** [comment]
> Same issue since the update... installation of an old version didn't solve the issue...
> 
> Does anyone has a solution?

Moved it to child bridge to keep homebridge running. Disabled it for 2 hours, now starts fine again...

**Comment by dubocr** [comment]
Could you please add config param "debug": true then repost logs when error occurs.
I published un update to fix homebridge restart when exception occurs.

If error is `RESOURCE_ACCESS_DENIED`, comment here.
If error is `AUTHENTICATION_ERROR`, comment on #387 

Thank you

**Comment by DaniS81** [comment]
> > Same issue since the update... installation of an old version didn't solve the issue...
> > Does anyone has a solution?
> 
> Moved it to child bridge to keep homebridge running. Disabled it for 2 hours, now starts fine again...

Disabled for some hour and after a restart it's working again...

**Comment by dubocr** [comment]
What are the logs before and after ?
Does the `{"level":30,"time":1663143351438,"pid":30021,"hostname":"raspberrypi","reqId":"req-5d","res":{"statusCode":200},"responseTime":30.405784964561462,"msg":"request completed"}` logs are from homtbridge-tahoma plugin ???

**Comment by byna** [comment]
I got this as well now:

[19/09/2022, 09:17:34] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[19/09/2022, 09:17:44] [TaHoma]  POST /login
[19/09/2022, 09:17:44] [TaHoma]  Enable event polling period every 900 sec
[19/09/2022, 09:17:44] [TaHoma]  POST /events/register
[19/09/2022, 09:32:44] [TaHoma]  POST /events/549c2d65-ac10-3e01-6399-5f116fc8a72a/fetch
[19/09/2022, 09:32:44] [TaHoma]  Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[19/09/2022, 09:32:44] [TaHoma]  Disable event polling

**Comment by sprihar** [comment]
+1 also getting the same issue.

**Comment by dubocr** [comment]
> I got this as well now:
> 
> [19/09/2022, 09:17:34] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED) [19/09/2022, 09:17:44] [TaHoma] POST /login [19/09/2022, 09:17:44] [TaHoma] Enable event polling period every 900 sec [19/09/2022, 09:17:44] [TaHoma] POST /events/register [19/09/2022, 09:32:44] [TaHoma] POST /events/549c2d65-ac10-3e01-6399-5f116fc8a72a/fetch [19/09/2022, 09:32:44] [TaHoma] Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED) [19/09/2022, 09:32:44] [TaHoma] Disable event polling

Hi,

It seems you changed the `pollingPeriod` to 900 (sec), that's why your session expires between each `fetch` requests.
You should leave the default `pollingPeriod` value or set it to `0` to disable polling (will have the same effect as setting it to 900 because if session expires every changes are missed)

**Comment by dubocr** [comment]
> +1 also getting the same issue.

If the previous answer doesn't apply for you, please enable `"debug": true` parameter in your config then send full log since plugin startup until the first `Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)`.

Thank you.

**Comment by sprihar** [comment]
> > +1 also getting the same issue.
> 
> @sprihar If the previous answer doesn't apply for you, please enable `"debug": true` parameter in your config then send full log since plugin startup until the first `Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)`.
> 
> Thank you.

Hi @dubocr Please see the below logs in debug mode:


9/19/2022, 5:51:36 PM Tahoma Bridge Configuration change
9/19/2022, 5:51:36 PM Tahoma Bridge tahomabridge stopping
9/19/2022, 5:51:42 PM Tahoma Bridge Tahoma Bridge starting
9/19/2022, 5:51:47 PM Tahoma Bridge Loaded plugin 'homebridge-tahoma'
9/19/2022, 5:51:47 PM Tahoma Bridge [ DEBUG ] Registering platform 'homebridge-tahoma.Tahoma'
9/19/2022, 5:51:47 PM Tahoma Bridge Loading 1 platforms...
9/19/2022, 5:51:47 PM Tahoma Bridge TaHoma  POST /login
9/19/2022, 5:51:48 PM Tahoma Bridge Bridge is running on port 51836.
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma  Enable event polling period every 60 sec
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma  GET /setup/devices
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma  GET /setup/location
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma  POST /events/register
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma Configure device 2nd Floor
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma   Screen > UpDownScreen
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma Configure device Living Room
9/19/2022, 5:51:48 PM Tahoma Bridge TaHoma   Screen > UpDownScreen
9/19/2022, 5:52:48 PM Tahoma Bridge TaHoma  POST /events/57bc684c-ac10-3201-67f0-2025d7ced3f8/fetch
9/19/2022, 5:52:48 PM Tahoma Bridge TaHoma  Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:52:48 PM Tahoma Bridge TaHoma  Disable event polling
9/19/2022, 5:52:48 PM Tahoma Bridge TaHoma [ ERROR ] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:52:58 PM Tahoma Bridge TaHoma  POST /login
9/19/2022, 5:52:59 PM Tahoma Bridge TaHoma  Enable event polling period every 60 sec
9/19/2022, 5:52:59 PM Tahoma Bridge TaHoma  POST /events/register
9/19/2022, 5:53:59 PM Tahoma Bridge TaHoma  POST /events/57bd7c4a-ac10-3201-67f0-2025006d3371/fetch
9/19/2022, 5:53:59 PM Tahoma Bridge TaHoma  Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:53:59 PM Tahoma Bridge TaHoma  Disable event polling
9/19/2022, 5:53:59 PM Tahoma Bridge TaHoma [ ERROR ] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:54:09 PM Tahoma Bridge TaHoma  POST /login
9/19/2022, 5:54:10 PM Tahoma Bridge TaHoma  Enable event polling period every 60 sec
9/19/2022, 5:54:10 PM Tahoma Bridge TaHoma  POST /events/register
9/19/2022, 5:54:37 PM Tahoma Bridge TaHoma [Living Room] my[]
9/19/2022, 5:54:37 PM Tahoma Bridge TaHoma [2nd Floor] my[]
9/19/2022, 5:54:37 PM Tahoma Bridge TaHoma  POST /exec/apply
9/19/2022, 5:54:37 PM Tahoma Bridge TaHoma  Change event polling period to 5 sec
9/19/2022, 5:54:37 PM Tahoma Bridge TaHoma  POST /exec/apply
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma [Living Room] my NOT_TRANSMITTED
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma [Living Room] my TRANSMITTED
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma [2nd Floor] my NOT_TRANSMITTED
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma [2nd Floor] my TRANSMITTED
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma [Living Room] my IN_PROGRESS
9/19/2022, 5:54:42 PM Tahoma Bridge TaHoma [2nd Floor] my IN_PROGRESS
9/19/2022, 5:54:47 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:54:52 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:54:57 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:55:02 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:55:07 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:55:12 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:55:12 PM Tahoma Bridge TaHoma [Living Room] my COMPLETED
9/19/2022, 5:55:12 PM Tahoma Bridge TaHoma [2nd Floor] my COMPLETED
9/19/2022, 5:55:17 PM Tahoma Bridge TaHoma  Change event polling period to 60 sec
9/19/2022, 5:56:17 PM Tahoma Bridge TaHoma  POST /events/57be909f-ac10-3201-67f0-202580c32ef5/fetch
9/19/2022, 5:56:17 PM Tahoma Bridge TaHoma  Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:56:17 PM Tahoma Bridge TaHoma  Disable event polling
9/19/2022, 5:56:17 PM Tahoma Bridge TaHoma [ ERROR ] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:56:27 PM Tahoma Bridge TaHoma  POST /login
9/19/2022, 5:56:28 PM Tahoma Bridge TaHoma  Enable event polling period every 60 sec
9/19/2022, 5:56:28 PM Tahoma Bridge TaHoma  POST /events/register
9/19/2022, 5:57:28 PM Tahoma Bridge TaHoma  POST /events/57c0ac79-ac10-3201-67f0-2025ea05739a/fetch
9/19/2022, 5:57:28 PM Tahoma Bridge TaHoma  Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:57:28 PM Tahoma Bridge TaHoma  Disable event polling
9/19/2022, 5:57:28 PM Tahoma Bridge TaHoma [ ERROR ] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
9/19/2022, 5:57:38 PM Tahoma Bridge TaHoma  POST /login
9/19/2022, 5:57:38 PM Tahoma Bridge TaHoma  Enable event polling period every 60 sec
9/19/2022, 5:57:38 PM Tahoma Bridge TaHoma  POST /events/register

**Comment by Tontonpat** [comment]
`[9/20/2022, 8:33:01 AM] [Tahoma]  POST /events/59825857-ac10-3e01-6399-5f11f68ff165/fetch
[9/20/2022, 8:33:01 AM] [Tahoma]  Session expired: Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[9/20/2022, 8:33:01 AM] [Tahoma]  Disable event polling
[9/20/2022, 8:33:01 AM] [Tahoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[9/20/2022, 8:33:11 AM] [Tahoma]  POST /login
[9/20/2022, 8:33:11 AM] [Tahoma] API client will be locked for 60 seconds because of bad credentials or temporary service outage. You can restart plugin to force login retry (not recommanded except if you think your credentials are wrong).
[9/20/2022, 8:33:11 AM] [Tahoma] Registration error - Error 401 Bad credentials (AUTHENTICATION_ERROR)`

**Comment by dubocr** [comment]
Thank you @sprihar,
Can you try to change the config `"pollingPeriod": 30` (try at 30, then if you don't notice any changes, try at 15 then 10).

@Tontonpat, c'est sur ta config cloud ? A combien est ton pollingPeriod ?

**Comment by Tontonpat** [comment]
@dubocr Oui sur la config cloud
`"pollingPeriod": 30,
            "refreshPeriod": 10, `

**Comment by sprihar** [comment]
> Thank you @sprihar, Can you try to change the config `"pollingPeriod": 30` (try at 30, then if you don't notice any changes, try at 15 then 10).
> 
> @Tontonpat, c'est sur ta config cloud ? A combien est ton pollingPeriod ?

@dubocr  thank you, try now. Will report back in a few hours and provide updated logs.

**Comment by sprihar** [comment]
@dubocr I changed the pollingperiod to 15, 10 and 5. All three options are not returning the error any longer. Is there any benefit to keeping it at 5 instead of 15?

**Comment by dubocr** [comment]
> @dubocr I changed the pollingperiod to 15, 10 and 5. All three options are not returning the error any longer. Is there any benefit to keeping it at 5 instead of 15?

The default value is 60. Set it to the highest functional value as this will overload Somfy servers.

**Comment by sprihar** [comment]
> > @dubocr I changed the pollingperiod to 15, 10 and 5. All three options are not returning the error any longer. Is there any benefit to keeping it at 5 instead of 15?
> 
> The default value is 60. Set it to the highest functional value as this will overload Somfy servers.

@dubocr  this worked perfectly. Thank you for all your help!

**Comment by byna** [comment]
I set pollingperiod to 15 and I still get the following:

[21/09/2022, 07:53:36] [TaHoma] Polling error - Error 502
[21/09/2022, 07:54:23] [TaHoma] Polling error - Error 502
[21/09/2022, 07:55:46] [TaHoma] Polling error - Error 503
[21/09/2022, 07:58:03] [TaHoma] Polling error - read ECONNRESET
[21/09/2022, 08:00:31] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:01:12] [TaHoma] Polling error - Error 502
[21/09/2022, 08:03:46] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:04:04] [TaHoma] Error 503
[21/09/2022, 08:05:12] [TaHoma] Polling error - Error 503
[21/09/2022, 08:07:46] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:10:15] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:11:42] [TaHoma] Polling error - Error 503
[21/09/2022, 08:12:40] [TaHoma] Polling error - Error 503
[21/09/2022, 08:15:17] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:17:45] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:18:47] [TaHoma] Polling error - Error 503
[21/09/2022, 08:21:15] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:23:44] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:26:17] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:27:13] [TaHoma] Polling error - Error 503
[21/09/2022, 08:31:45] [TaHoma] Polling error - read ECONNRESET
[21/09/2022, 08:33:13] [TaHoma] Error 503
[21/09/2022, 08:34:03] [TaHoma] Polling error - read ECONNRESET
[21/09/2022, 08:36:27] [TaHoma] Polling error - read ECONNRESET
[21/09/2022, 08:39:00] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:41:29] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:42:32] [TaHoma] Polling error - Error 503
[21/09/2022, 08:43:40] [TaHoma] Polling error - Error 503
[21/09/2022, 08:44:39] [TaHoma] Polling error - Error 503
[21/09/2022, 08:46:10] [TaHoma] Polling error - Error 502
[21/09/2022, 08:47:11] [TaHoma] Polling error - Error 503
[21/09/2022, 08:49:14] [TaHoma] Polling error - Error 503
[21/09/2022, 08:50:19] [TaHoma] Polling error - Error 503
[21/09/2022, 08:51:09] [TaHoma] Polling error - Error 503
[21/09/2022, 08:53:46] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:54:48] [TaHoma] Polling error - Error 503
[21/09/2022, 08:57:16] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 08:58:28] [TaHoma] Polling error - Error 503
[21/09/2022, 09:01:01] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:02:59] [TaHoma] Polling error - Error 503
[21/09/2022, 09:04:31] [TaHoma] read ECONNRESET
[21/09/2022, 09:05:33] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:08:01] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:10:30] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:12:26] [TaHoma] Polling error - Error 503
[21/09/2022, 09:15:01] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:16:05] [TaHoma] Polling error - Error 503
[21/09/2022, 09:16:56] [TaHoma] Polling error - Error 503
[21/09/2022, 09:18:33] [TaHoma] Polling error - Error 502
[21/09/2022, 09:20:59] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:22:24] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[21/09/2022, 09:25:20] [TaHoma] Polling error - connect ETIMEDOUT 178.32.15.131:443
[21/09/2022, 09:26:14] [TaHoma] Polling error - Error 502
[21/09/2022, 09:27:14] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED)
[21/09/2022, 09:27:26] [TaHoma] Registration error - Error 502

**Comment by byna** [comment]
I set pollingPeriod to 10 and it seems to work most of the time👍
I get the following error message sometimes though:

[29/09/2022, 07:01:54] [TaHoma] Error 400 Too many asynchronous jobs, try again later (job was Full refresh all states) (TOO_MANY_OPERATIONS_IN_PROGRESS)

**Comment by steve-mahdi** [comment]
[10/26/2022, 8:13:47 PM] [TaHoma] Error 400 Too many asynchronous jobs, try again later (job was Full refresh all states) (TOO_MANY_OPERATIONS_IN_PROGRESS)
[10/27/2022, 1:33:05 AM] [TaHoma] Polling error - connect ETIMEDOUT 178...:
[10/27/2022, 1:34:09 AM] [TaHoma] Polling error - Error 401 Not authenticated (RESOURCE_ACCESS_DENIED
[10/27/2022, 5:34:42 AM] [TaHoma] Polling error - connect ETIMEDOUT 178...:
[10/27/2022, 5:36:41 AM] [TaHoma] Registration error - connect ETIMEDOUT 178...:
[10/27/2022, 5:36:41 AM] [TaHoma] connect ETIMEDOUT 178...:
[10/27/2022, 6:00:02 AM] [TaHoma] [Bedroom Shutter] open connect ETIMEDOUT 178...:
[10/27/2022, 6:00:02 AM] [TaHoma] [Dining Room Shutter] open connect ETIMEDOUT 178...:
[10/27/2022, 6:00:02 AM] [TaHoma] [Sara Room front Shutter] open connect ETIMEDOUT 178...:
[10/27/2022, 6:00:02 AM] [TaHoma] [Kitchen Shutter] open connect ETIMEDOUT 178...:
[10/27/2022, 6:00:02 AM] [TaHoma] [Sara Room Left Shutter] open connect ETIMEDOUT 178...:

can you help me please ?
device : Tahoma Switch
