### ISSUE TITLE
RangeError: Maximum call stack size exceeded (v2.2.40)

### ISSUE THREAD

**Issue by bkarakashev** [dubocr/homebridge-tahoma#397]
Plugin Version: v2.2.40

[TaHoma] RangeError: Maximum call stack size exceeded
    at Array.shift (<anonymous>)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:82)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)
    at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)

**Comment by Tekklab** [comment]
> Plugin Version: v2.2.40
> 
> [TaHoma] RangeError: Maximum call stack size exceeded at Array.shift () at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:82) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71) at Function.debug (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:54:71)

same here, reboot & reboot until i disabled the plugin

**Comment by bkarakashev** [comment]
I rollback to v2.2.39 and this worked for me. I guess there is some issue with v2.2.40.

**Comment by Tontonpat** [comment]
Bonjour Romain,
Pareil chez moi, mais en restaurant la version V2.2.39, ça m'a perdu toute ma config dans HomeKit...

**Comment by dubocr** [comment]
Fix en v2.2.41
