### ISSUE TITLE
TaHoma Switch + Passerelle Daikin -> [UNSUPPORTED_OPERATION]

### ISSUE THREAD

**Issue by SandraBox** [dubocr/homebridge-tahoma#420]
TaHoma Switch + Passerelle Daikin
Homebridge TaHoma v2.2.48
IOS 16
Daikin:
- PAC Altherma
- Clim Perfera
- Clim Stylish

Bonjour,

Lorsque je démarre mon serveur Homebridge mon matértiel remonte correctement dans Homekit.

Après utilisation du bouton pour le réglage de consigne le matériel ne répond plus !

Voici le log dans Homebridge:

[05/10/2022, 10:36:03] [TaHoma] [Perfera] auto[]
[05/10/2022, 10:36:03] [TaHoma] POST /exec/apply
[05/10/2022, 10:36:03] [TaHoma] [Perfera] auto Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/fa8397fe-b23f-465b-b8b9-90bf15f565fa_climateControl_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION)
[05/10/2022, 10:36:03] [homebridge-tahoma] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/fa8397fe-b23f-465b-b8b9-90bf15f565fa_climateControl_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION). See https://homebridge.io/w/JtMGR for more info.
[05/10/2022, 10:36:03] [homebridge-tahoma] Error: Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/fa8397fe-b23f-465b-b8b9-90bf15f565fa_climateControl_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION)
    at OverkizClient.execute (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:165:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:171:44)

[05/10/2022, 10:36:38] [TaHoma] [Altherma] auto[]
[05/10/2022, 10:36:38] [TaHoma] POST /exec/apply
[05/10/2022, 10:36:38] [TaHoma] [Altherma] auto Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/10b029e7-484c-4519-b22e-c14be4b7a71c_climateControlMainZone_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION)
[05/10/2022, 10:36:38] [homebridge-tahoma] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/10b029e7-484c-4519-b22e-c14be4b7a71c_climateControlMainZone_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION). See https://homebridge.io/w/JtMGR for more info.
[05/10/2022, 10:36:38] [homebridge-tahoma] Error: Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/10b029e7-484c-4519-b22e-c14be4b7a71c_climateControlMainZone_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION)
    at OverkizClient.execute (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:165:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:171:44)

[05/10/2022, 10:36:53] [TaHoma] [Stylish] auto[]
[05/10/2022, 10:36:53] [TaHoma] POST /exec/apply
[05/10/2022, 10:36:53] [TaHoma] [Stylish] auto Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/78001793-f434-45bf-8db1-8f606aa6f844_climateControl_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION)
[05/10/2022, 10:36:53] [homebridge-tahoma] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/78001793-f434-45bf-8db1-8f606aa6f844_climateControl_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION). See https://homebridge.io/w/JtMGR for more info.
[05/10/2022, 10:36:53] [homebridge-tahoma] Error: Error 400 No such command : auto on device ogcp://OGCP-S-DAIKIN-62dae05184bf2f001dc29fda/78001793-f434-45bf-8db1-8f606aa6f844_climateControl_1 (ogp:HVACZone) (UNSUPPORTED_OPERATION)
    at OverkizClient.execute (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:165:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:171:44)

Merci,
Sandra
![1](https://user-images.githubusercontent.com/115086423/194067817-1380d1c0-c693-46d5-b726-526293c41eca.jpg)
![2](https://user-images.githubusercontent.com/115086423/194067822-150a8261-4468-4fc6-92da-604e9f87acb1.jpg)
![3](https://user-images.githubusercontent.com/115086423/194067823-79736b60-8816-4faa-b5ec-eda3f6fe3455.jpg)

**Comment by SandraBox** [comment]
Bonjour,

Passer en mode "Local API" pourrait il m'aider à solutionner mon problème ?

Merci,
Sandra

**Comment by dubocr** [comment]
Bonjour,

Je vous invite à ouvrir une demande en suivant la procédure pour gérer cet équipement.

Merci.

**Comment by SandraBox** [comment]
Bonjour,

je n'arrive pas à générer le report.

Est ce suffisant ?

Merci,
Sandra

Voici les configurations de mes devices: 

***Gateway:*** 4706
***Device:*** HeatingSystem > DynamicHvacZone

***States***

<img width="1432" alt="devices" src="https://user-images.githubusercontent.com/115086423/197235305-6bfcb6bc-835d-4c85-8eed-1553059a5cf4.png">
[Devices.zip](https://github.com/dubocr/homebridge-tahoma/files/9840551/Devices.zip)
