### ISSUE TITLE
Coalesce HomeKit actions to make scenes with a large number of devices reliable

### ISSUE THREAD

**Issue by IngmarStein** [dubocr/homebridge-tahoma#423]
In https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/64, I described how actuating a HomeKit scene with a dozen Somfy devices is unreliable (not all devices act on the request, some blinds being stuck in the middle - it takes multiple attempts to get to the desired state).

Somfy's response was to use a single non-persistent action group containing the individual actions to avoid overloading the TaHoma. I still think that the box should better handle this situation and sequence requests itself, but that's unlikely to happen. As a workaround, homebridge-tahoma could coalesce actions that are sent in short succession in a single action group. This likely adds some latency, but maybe it's possible to keep the time period in which actions are coalesced short enough. The reliability gain should more than make up for that.

Does that sound feasible?

**Comment by dubocr** [comment]
Hi,

This is already done by grouping actions sent simultaneously by HomeKit in the same action bulk.
You can check it by [browsing your config](http://dev.duboc.pro/overkiz) an notice the `Execute Scene` label for action in history
<img width="563" alt="Capture d’écran 2022-10-13 à 11 40 09" src="https://user-images.githubusercontent.com/5015156/195562810-3fea8c35-ecd8-409c-b751-713e89fefd95.png">

**Comment by IngmarStein** [comment]
I don't see actions triggered by HomeKit in the history. Here's the homebridge log for two actions manually executed today (2022-10-13):
```
[10/13/2022, 8:20:54 PM] [TaHoma] [Treppenhaus] close[]
[10/13/2022, 8:20:54 PM] [TaHoma] [Schlafzimmermarkise] undeploy[]
[10/13/2022, 8:20:54 PM] [TaHoma] [Küche] close[]
[10/13/2022, 8:20:54 PM] [TaHoma] [Esszimmer] close[]
[10/13/2022, 8:20:54 PM] [TaHoma] [Gästebad EG] close[]
[10/13/2022, 8:21:34 PM] [TaHoma] [Treppenhaus] close COMPLETED
[10/13/2022, 8:21:34 PM] [TaHoma] [Schlafzimmermarkise] undeploy COMPLETED
[10/13/2022, 8:21:34 PM] [TaHoma] [Küche] close COMPLETED
[10/13/2022, 8:21:34 PM] [TaHoma] [Esszimmer] close COMPLETED
[10/13/2022, 8:21:34 PM] [TaHoma] [Gästebad EG] close COMPLETED
[10/13/2022, 8:23:42 PM] [TaHoma] [Treppenhaus] close[]
[10/13/2022, 8:23:42 PM] [TaHoma] [Schlafzimmermarkise] undeploy[]
[10/13/2022, 8:23:42 PM] [TaHoma] [Küche] close[]
[10/13/2022, 8:23:42 PM] [TaHoma] [Esszimmer] close[]
[10/13/2022, 8:23:42 PM] [TaHoma] [Gästebad EG] close[]
[10/13/2022, 8:23:55 PM] [Homebridge UI] Starting terminal session
[10/13/2022, 8:24:23 PM] [TaHoma] [Treppenhaus] close COMPLETED
[10/13/2022, 8:24:23 PM] [TaHoma] [Schlafzimmermarkise] undeploy COMPLETED
[10/13/2022, 8:24:23 PM] [TaHoma] [Küche] close COMPLETED
[10/13/2022, 8:24:23 PM] [TaHoma] [Esszimmer] close COMPLETED
[10/13/2022, 8:24:23 PM] [TaHoma] [Gästebad EG] close COMPLETED
```
but there's no corresponding entry in the history:
<img width="1198" alt="Bildschirm­foto 2022-10-13 um 20 25 29" src="https://user-images.githubusercontent.com/490610/195676703-3c1c5cc7-626d-4fdd-827b-85815fd9c71f.png">

**Comment by dubocr** [comment]
Ok, you can add `"debug": true` to you plugin config this will let see that only one request is made for each group of action.

**Comment by IngmarStein** [comment]
Thanks for the pointer to the debug output. It confirms that only a single POST to /exec/apply is done, but also a lot of ECONNREFUSED errors from the box. Following the execution below, only some of the blinds were closed:
```
[10/14/2022, 8:16:53 PM] [TaHoma] [Treppenhaus] close[]
[10/14/2022, 8:16:53 PM] [TaHoma] [Schlafzimmermarkise] undeploy[]
[10/14/2022, 8:16:53 PM] [TaHoma] [Küche] close[]
[10/14/2022, 8:16:53 PM] [TaHoma] [Esszimmer] close[]
[10/14/2022, 8:16:53 PM] [TaHoma] [Gästebad EG] close[]
[10/14/2022, 8:16:54 PM] [TaHoma]  POST /exec/apply
[10/14/2022, 8:16:54 PM] [TaHoma]  Error: connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:16:54 PM] [TaHoma] [Treppenhaus] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:16:54 PM] [TaHoma] [Schlafzimmermarkise] undeploy connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:16:54 PM] [TaHoma] [Küche] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:16:54 PM] [TaHoma] [Esszimmer] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:16:54 PM] [TaHoma] [Gästebad EG] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:16:54 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:16:54 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:16:54 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:16:54 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:16:54 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:17:09 PM] [TaHoma] [Küche] close[]
[10/14/2022, 8:17:09 PM] [TaHoma] [Esszimmer] close[]
[10/14/2022, 8:17:09 PM] [TaHoma] [Schlafzimmermarkise] undeploy[]
[10/14/2022, 8:17:09 PM] [TaHoma] [Gästebad EG] close[]
[10/14/2022, 8:17:09 PM] [TaHoma] [Treppenhaus] close[]
[10/14/2022, 8:17:09 PM] [TaHoma]  POST /exec/apply
[10/14/2022, 8:17:09 PM] [TaHoma]  Error: connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:17:09 PM] [TaHoma] [Küche] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:17:09 PM] [TaHoma] [Esszimmer] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:17:09 PM] [TaHoma] [Schlafzimmermarkise] undeploy connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:17:09 PM] [TaHoma] [Gästebad EG] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:17:09 PM] [TaHoma] [Treppenhaus] close connect ECONNREFUSED 192.168.1.55:8443
[10/14/2022, 8:17:09 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:17:09 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:17:09 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:17:09 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
[10/14/2022, 8:17:09 PM] [TaHoma] ExecutionError: connect ECONNREFUSED 192.168.1.55:8443
    at OverkizClient.execute (/volume1/homebridge/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:176:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  state: 'FAILED'
}
```

**Comment by dubocr** [comment]
Duplicate error message was fixed in latest release. This won't change anything in the behaviour. In this case, homebridge can't connect to tahoma bridge because of bad address, developer mode inactive or something like that.

**Comment by IngmarStein** [comment]
Thank you. Fwiw: developer mode was active all the time and the IP remained the same (see identical `curl` invocations above). I think it was an internal error inside the box.
