### ISSUE TITLE
After switching to Local API there is a strange error

### ISSUE THREAD

**Issue by sabiwa** [dubocr/homebridge-tahoma#454]
When I have my settings right with the cloud solution, I get the following error when switching to local api following the descriptions in your readme.

[1/18/2023, 11:20:31 PM] [TaHoma] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/homebridge/node_modules/homebridge/src/platformAccessory.ts:71:9)
    at Platform.discoverDevices (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:175:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}

I have the feeling it is giving this error when adding the 3rd scene

**Comment by sabiwa** [comment]
I have redone this test with a new setup and with creating new credentials. I have no idea where the empty display name for an activity comes from.

Is there anything I can do to clarify the topic more?
