### ISSUE TITLE
Local API - Error

### ISSUE THREAD

**Issue by sabiwa** [dubocr/homebridge-tahoma#477]
I have my configde as Somfy Europe and everything works. But I wanted to use the local service and have followed the settings have created the local API and restarted the homebridge but getting the following error message:

[5/14/2023, 11:34:24 PM] [TaHoma] 19 devices discovered
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Bovenste balk woonkamer voorkant
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Bovenste balk woonkamer voorkant
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownTopDownScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Eetkamer 
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Eetkamer 
[5/14/2023, 11:34:24 PM] [TaHoma]   Curtain > UpDownDualCurtain
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Bovenste balk werkkamer voorkant
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Bovenste balk werkkamer voorkant
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownTopDownScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Onderste balk eetkamer 
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Onderste balk eetkamer 
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownBottomUpScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Bovenste balk woonkamer zijkant 
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Bovenste balk woonkamer zijkant 
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownTopDownScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Onderste balk woonkamer voorkant 
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Onderste balk woonkamer voorkant 
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownBottomUpScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Onderste balk.werkkamer voorkant
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Onderste balk.werkkamer voorkant
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownBottomUpScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Slaapkamer 
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Slaapkamer 
[5/14/2023, 11:34:24 PM] [TaHoma]   Curtain > UpDownDualCurtain
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Bovenste balk eetkamer
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Bovenste balk eetkamer
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownTopDownScreen
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory: Onderste balk woonkamer zijkant 
[5/14/2023, 11:34:24 PM] [TaHoma] Configure device Onderste balk woonkamer zijkant 
[5/14/2023, 11:34:24 PM] [TaHoma]   Screen > UpDownBottomUpScreen
[5/14/2023, 11:34:24 PM] [TaHoma] GET /actionGroups
[5/14/2023, 11:34:24 PM] [TaHoma] Map scene avond
[5/14/2023, 11:34:24 PM] [TaHoma] Map scene Alles Dicht 
[5/14/2023, 11:34:24 PM] [TaHoma] Map scene overdag
[5/14/2023, 11:34:24 PM] [TaHoma] Map scene TV kijken 
[5/14/2023, 11:34:24 PM] [TaHoma] Create accessory 
[5/14/2023, 11:34:24 PM] [TaHoma] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/homebridge/node_modules/homebridge/src/platformAccessory.ts:71:9)
    at Platform.discoverDevices (/homebridge/node_modules/homebridge-tahoma/src/Platform.ts:175:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
[5/14/2023, 11:34:24 PM] [TaHoma] Retry in 60 sec...

Any suggestions?

**Comment by sabiwa** [comment]
In my Tahoma app I can't see any accessoire with an empty displayName

**Comment by sabiwa** [comment]
Any updates ?
I would love to move to local connection as in the cloud connection sometimes is a big delay noticeable

**Comment by IngmarStein** [comment]
Have you tried `"exposeScenarios": false`?

**Comment by sabiwa** [comment]
Not yet because I mainly use the scenarios from Tahoma in Homekit but I will give it a try and see how it works tomorrow. Thanks for the suggestion
