### ISSUE TITLE
Bug at launch with HitachiHeatingSystem

### ISSUE THREAD

**Issue by fafoulon** [dubocr/homebridge-tahoma#51]
Bonjour,

J'ai un nouveau bug au démarrage d'homebridge :

`Oct 18 10:18:43 rasphomebridge homebridge[1661]: /usr/lib/node_modules/homebridge-tahoma/accessories/HitachiHeatingSystem.js:209

Oct 18 10:18:43 rasphomebridge homebridge[1661]: var converted = parseInt(value.substring(0,value.length-3));
Oct 18 10:18:43 rasphomebridge homebridge[1661]: ^
Oct 18 10:18:43 rasphomebridge homebridge[1661]: TypeError: value.substring is not a function
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at HitachiHeatingSystem.onStateUpdate (/usr/lib/node_modules/homebridge-tahoma/accessories/HitachiHeatingSystem.js:209:41)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at /usr/lib/node_modules/homebridge-tahoma/index.js:97:21
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at /usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:176:5
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at Request.authCallback [as _callback] (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:208:17)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at Request.self.callback (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at emitTwo (events.js:106:13)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at Request.emit (events.js:194:7)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at Request.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at emitOne (events.js:96:13)
Oct 18 10:18:43 rasphomebridge homebridge[1661]: at Request.emit (events.js:191:7)`

**Comment by fafoulon** [comment]
Apparemment l'api a changé? en enlevant tous les substring(0,-3) ça marche. (ils ont viré le " °C" je pense)

**Comment by fafoulon** [comment]
De rien, il ne doit y avoir que moi qui l'utilise de toute façon :-D

**Comment by fafoulon** [comment]
Je viens d'essayer ton code, mais toujours des erreurs, parce qu'il n'a plus de °C ni °F, il faudrait enlever les "replace" et aussi il reste un substring(0,+3) plus haut.

Mais je viens de tester avec ma clim, et j'ai des erreurs de valeurs :

`FROM 0/19 TO 1/14
Oct 25 10:10:24 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:24 AM] [Tahoma] [Etage] globalControl["on",14,"auto","heating","manu"]
Oct 25 10:10:36 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:36 AM] [Tahoma] ovp:TemperatureChangeState => -233
Oct 25 10:10:37 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:37 AM] [Tahoma] FROM 0/19 TO 1/21.4
Oct 25 10:10:37 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:37 AM] [Tahoma] [Etage] globalControl["on",21.4,"auto","heating","manu"]
Oct 25 10:10:37 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:37 AM] [Tahoma] Error 400 Managed action group is invalid : globalControl() : Invalid value for command parameter p2 : expected integer value but got 21.4 (UNSPECIFIED_ERROR)
Oct 25 10:10:37 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:37 AM] [Tahoma] ovp:TemperatureChangeState => 23
Oct 25 10:10:42 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:42 AM] [Tahoma] [Etage] globalControl COMPLETED
Oct 25 10:10:42 rasphomebridge homebridge[10656]: [10/25/2018, 10:10:42 AM] [Tahoma] ovp:TemperatureChangeState => -234
`

**Comment by fafoulon** [comment]
ça va être pratique des valeurs comme ça :

`ovp:TemperatureChangeState => -234
[10/25/2018, 10:18:46 AM] [Tahoma] ovp:TemperatureChangeState => 23

[10/25/2018, 10:18:46 AM] [Tahoma] ovp:TemperatureChangeState => -234
[10/25/2018, 10:18:46 AM] [Tahoma] ovp:TemperatureChangeState => -233
[10/25/2018, 10:28:46 AM] [Tahoma] ovp:TemperatureChangeState => 23
[10/25/2018, 10:28:46 AM] [Tahoma] ovp:TemperatureChangeState => -231
[10/25/2018, 10:28:46 AM] [Tahoma] ovp:TemperatureChangeState => -231
[10/25/2018, 10:38:46 AM] [Tahoma] ovp:TemperatureChangeState => 23
[10/25/2018, 10:38:46 AM] [Tahoma] ovp:TemperatureChangeState => -233
[10/25/2018, 10:38:46 AM] [Tahoma] ovp:TemperatureChangeState => -232
[10/25/2018, 10:48:46 AM] [Tahoma] ovp:TemperatureChangeState => 23
[10/25/2018, 10:48:46 AM] [Tahoma] ovp:TemperatureChangeState => -233
[10/25/2018, 10:48:46 AM] [Tahoma] ovp:TemperatureChangeState => -233`
