### ISSUE TITLE
Problems after updating 1.29

### ISSUE THREAD

**Issue by henkied** [dubocr/homebridge-tahoma#61]
I have an issue after updating to version 1.29

[1/21/2019, 4:34:10 PM] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.2
/homebridge/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:370
                                                        this.targetState.updateValue(this.temperature.comfort;
                                                                                                      ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by dubocr** [comment]
Fixed in 1.30
