### ISSUE TITLE
Error with more 10 blinds

### ISSUE THREAD

**Issue by ChrisJary** [dubocr/homebridge-tahoma#7]
Hello,
I've an error when I start a scene with more 10 blinds, is it possible to control more ?
This limit is in the plugin or in homekit?
Best Regards
Christopher

**Comment by dubocr** [comment]
Hi Christopher,

What kind of error do you have ? Have you log trace ? I have no knowledge of restriction but if this come from Tahoma you will have some error log in homebridge : 
`sudo journalctl | grep homebridge`

Best

**Comment by ChrisJary** [comment]
Hello,
the error in hombridge: 
[2017-07-25 08:31:07] [Tahoma] Error 400 Execution queue is full (soft limit: 10) (EXEC_QUEUE_FULL)

**Comment by dubocr** [comment]
Hi,

Seem this is a TaHoma API restriction so if you want to control more than 10 device with a scene, you have to create a TaHoma scene which will appear as on/off switch in homebridge.

**Comment by ChrisJary** [comment]
Hi,
ok, the scene create in TaHoma don't appear in home...
I will test to create an automation with a fake button who control many scene.

**Comment by dubocr** [comment]
Hi,
Sorry, to expose TaHoma scenes as on/off switch you have to add the folowing line in your config file :
“exposeScenarios“: true

**Comment by WTell** [comment]
Hi,

I'm also experiencing this issue. I'm getting:

> [6/25/2018, 5:00:03 PM] [Tahoma] Error 400 Execution queue is full on gateway: #XXXX-XXXX-XXXX (soft limit: 10) (EXEC_QUEUE_FULL)

While this might be a limit of the Somfy API, I believe that homebridge-tahoma needs to implement some sort of fix to work around it. As a user, I should be able to make a HomeKit Scene that consists of more than 10 devices without thinking about whatever API restrictions lie behind.

Cheers,

**Comment by dubocr** [comment]
Hi,

Yes, that’s true homebridge-tahoma needs to implement a work around.

Best,

**Comment by joel-lieberherr** [comment]
Hi,

I have the same problem with more than 10 blinds. And when I tried to expose the TaHoma scenes I get the following error:
ReferenceError: Service is not defined
    at new ScenarioAccessory (/usr/local/lib/node_modules/homebridge-tahoma/index.js:226:17)
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:200:32
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:193:5
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:216:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
What could be the problem? 
Homebridge is running on my iMac:
+-- homebridge@0.4.49
+-- homebridge-tahoma@0.2.2
Best regards
Joel

**Comment by dubocr** [comment]
Hi,
Issue with Scénario must be fixed in last release 0.2.3.
May I’ll find a workaround for API limit to 10. Stay tuned

**Comment by joel-lieberherr** [comment]
Thanks! My Scenarios from the TaHoma-Box now show up! :-)

**Comment by dubocr** [comment]
Small improvement made. Command over quota (10) are postpone to be executed later (10 sec).
