### ISSUE TITLE
Cozytouch No such command : setHeatingTargetTemperature

### ISSUE THREAD

**Issue by raffoul** [dubocr/homebridge-tahoma#73]
Bonjour,
D'abord merci d'avoir mis à disposition un plugin pour homebridge :)

Je viens de le configurer pour la plateforme cozytouch.

Mon installation :
- Une PAC extensa DUO AI
- Navilink A58 x2 (RDC et étage)
- Cozytouch

A l'initialisation :

1) Mes thermostats sont identifiés en mode clim alors qu'ils sont en mode chauffage.

2) Beaucoup d'accessoires trouvés dont je ne connais l'utilité :
[21/03/2019, 19:56:47] [Cozytouch] Connecting Cozytouch server...
[21/03/2019, 19:56:49] [Cozytouch] Device found: 11
[21/03/2019, 19:56:49] [Cozytouch] Device type Pod unknown
[21/03/2019, 19:56:49] [Cozytouch] [HP_Actuator] device type: HeatingSystem, name: io:AtlanticPassAPCHeatPumpMainComponent, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [RdC] device type: HeatingSystem, name: io:AtlanticPassAPCHeatingAndCoolingZoneComponent, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#11)] device type: TemperatureSensor, name: io:AtlanticPassAPCZoneTemperatureSensor, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#2)] device type: WaterHeatingSystem, name: io:AtlanticPassAPCDHWComponent, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#3)] device type: TemperatureSensor, name: io:AtlanticPassAPCOutsideTemperatureSensor, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#4)] device type: ElectricitySensor, name: io:TotalElectricalEnergyConsumptionSensor, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#5)] device type: ElectricitySensor, name: io:DHWRelatedElectricalEnergyConsumptionSensor, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#6)] device type: ElectricitySensor, name: io:HeatingRelatedElectricalEnergyConsumptionSensor, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [Etage] device type: HeatingSystem, name: io:AtlanticPassAPCHeatingAndCoolingZoneComponent, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] [IO (****#9)] device type: TemperatureSensor, name: io:AtlanticPassAPCZoneTemperatureSensor, protocol: io
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'HP_Actuator'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'RdC'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#11)'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#2)'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#3)'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#4)'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#5)'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#6)'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'Etage'...
[21/03/2019, 19:56:49] [Cozytouch] Initializing platform accessory 'IO (*****#9)'...
 
3) Parmi tous ces accessoires, j'en ai trouvé 2 correspondant à des thermostats, visiblement celui du RDC et de l'étage. J'ai essayé de changer la température, en vain, la commande ne semble pas exister d'après les logs.

[21/03/2019, 19:58:22] [Cozytouch] [Etage] setHeatingOnOffState INITIALIZED
[21/03/2019, 19:58:22] [Cozytouch] Register listener
[21/03/2019, 19:58:23] [Cozytouch] [Etage] setHeatingOnOffState IN_PROGRESS
[21/03/2019, 19:58:23] [Cozytouch] [Etage] setHeatingOnOffState COMPLETED
[21/03/2019, 19:58:23] [Cozytouch] Unregister listener
[21/03/2019, 19:58:35] [Cozytouch] [Etage] setHeatingTargetTemperature[18.7]
[21/03/2019, 19:58:36] [Cozytouch] Error 400 Managed action group is invalid : No such command : setHeatingTargetTemperature on device io://********#8 (io:AtlanticPassAPCHeatingAndCoolingZoneComponent) (UNSPECIFIED_ERROR)
[21/03/2019, 19:58:36] [Cozytouch] [Etage] setHeatingTargetTemperature Error 400 Managed action group is invalid : No such command : setHeatingTargetTemperature on device io://********#8 (io:AtlanticPassAPCHeatingAndCoolingZoneComponent) (UNSPECIFIED_ERROR)

Quelqu'un a-t-il une idée pour m'aider résoudre ce problème de commande svp ?
Comment est-il possible de filtrer les accessoires trouvés pour ne remonter que les thermostats ou sondes de température ?

Merci

**Comment by dubocr** [comment]
Bonjour,

Peux-tu te connecter sur cette page stp : https://dev.duboc.pro/tools/setup

Pour exclure des device, utilise le paramètre "exclude" comme indiqué dans le readme.

Merci

**Comment by raffoul** [comment]
Bonjour,
C’est fait. Sympa l’affichage de l’api par device. 

C’est moi qui te remercie !

Il y a 3 modes sur la chaudière (eco/confort/derog). 
Le planning fait référence au mode eco ou confort en fonction de ma configuration pour passer d’une température à l’autre. Le mode derog me permet à l’aide du thermostat local ou de l’appli Cozytouch de lancer une dérogation pour un durée à définir. 

A priori les commandes à utiliser sont donc celles-ci :
setDerogatedTargetTemperature
setDerogationOnOffState
setDerogationTime

**Comment by dubocr** [comment]
Bonjour,

J'ai ajouté la gestion de cette PAC avec le fichier ci-dessous que tu peux mettre dans le dossier accessories en remplacement de l'actuel.
La partie chauffage est plutôt basique sur HomeKit du coup il est compliqué de faire matcher les système complexes que nous avons en france.
Dis moi déjà si ça démarre et tes remarques.
[HeatingSystem.zip](https://github.com/dubocr/homebridge-tahoma/files/3007164/HeatingSystem.zip)

J'ai fait le choix suivant :
- Si la PAC est en chauffage/rafraîchissement => changement de T° provoque une dérogation
- Si la PAC est en chauffage seul ou rafraîchissement seul => changement de T° provoque changement de T° de consigne éco/confort

**Comment by raffoul** [comment]
Bonjour,
Merci pour l’implémentation. J’obtiens la stack suivante. Une idée ?

`[26/03/2019, 19:48:57] [Cozytouch] [HP_Actuator] device type: HeatingSystem, name: io:AtlanticPassAPCHeatPumpMainComponent, protocol: io
[26/03/2019, 19:48:57] [Cozytouch] [RdC] device type: HeatingSystem, name: io:AtlanticPassAPCHeatingAndCoolingZoneComponent, protocol: io
/usr/local/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:489
                                this.states[name] = value;
                                                  ^

TypeError: Cannot set property 'core:StatusState' of undefined
    at HeatingSystem.onStateUpdate (/usr/local/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:489:23)
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:103:21
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:183:5
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:215:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)`

**Comment by dubocr** [comment]
Voila qui devrait commencer à marcher. Il y à 3 fichiers à remplacer.
[homebridge-tahoma.zip](https://github.com/dubocr/homebridge-tahoma/files/3010879/homebridge-tahoma.zip)

**Comment by raffoul** [comment]
Merci c’est mieux mais sans remplacement de l’index.js

Voici mes observations :
- les températures enregistrées ne correspondent pas à ce qui est affiché dans HomeKit. Si je met 18° je vais me retrouver avec 18,1 ou 17,9 dans les logs par exemple
- impossible d’executer le mode dérogation. Je ne sais pas comment mettre le mode heatingCooling. Je pensais que c’etait le mode auto. Une idée ?
- les températures ne sont pas affichées sur le thermostat  (cercle orange à 0) mais la température de consigne l’est correctement 

Ça ne fonctionne pas si je remplace index.js .
Error: Cannot find module './overkiz-api'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/accessories/index.js:3:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by dubocr** [comment]
Le fichier index.js est à placer dans le répertoire supérieur (à la racine du plugin).
Cela corrigera l'intégration des capteurs de T° dans le thermostat.
Je regarde pour le reste.

**Comment by dubocr** [comment]
Voici un nouveau jeu de fichiers après correction
[homebridge-tahoma.zip](https://github.com/dubocr/homebridge-tahoma/files/3032886/homebridge-tahoma.zip)

**Comment by raffoul** [comment]
Merci. 
J’obtiens l’erreur suivante 

/usr/local/lib/node_modules/homebridge-tahoma/index.js:118
                                                that.log.info('[' + device.label + ']' + ' device type: ' + uiClass + ', name: ' + device.controllableName + ', protocol: ' + protocol);
                                                                                                            ^

ReferenceError: uiClass is not defined
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:118:67
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:183:5
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:215:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/l

**Comment by dubocr** [comment]
Oui désolé peux-tu retélécharger le fichier le lien n'était pas bon.

Merci.

**Comment by raffoul** [comment]
Aucun module affiché. 
Je pense que ça vient de ce message : Device heating system ignored. 

02/04/2019, 20:57:54] [Cozytouch] [HP_Actuator] device type: HeatingSystem, name: io:AtlanticPassAPCHeatPumpMainComponent, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] Device HeatingSystem ignored
[02/04/2019, 20:57:54] [Cozytouch] [RdC] device type: HeatingSystem, name: io:AtlanticPassAPCHeatingAndCoolingZoneComponent, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#11)] device type: TemperatureSensor, name: io:AtlanticPassAPCZoneTemperatureSensor, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#2)] device type: WaterHeatingSystem, name: io:AtlanticPassAPCDHWComponent, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#3)] device type: TemperatureSensor, name: io:AtlanticPassAPCOutsideTemperatureSensor, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#4)] device type: ElectricitySensor, name: io:TotalElectricalEnergyConsumptionSensor, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] Device ElectricitySensor ignored
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#5)] device type: ElectricitySensor, name: io:DHWRelatedElectricalEnergyConsumptionSensor, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] Device ElectricitySensor ignored
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#6)] device type: ElectricitySensor, name: io:HeatingRelatedElectricalEnergyConsumptionSensor, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] Device ElectricitySensor ignored
[02/04/2019, 20:57:54] [Cozytouch] [Etage] device type: HeatingSystem, name: io:AtlanticPassAPCHeatingAndCoolingZoneComponent, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] [IO (16451345#9)] device type: TemperatureSensor, name: io:AtlanticPassAPCZoneTemperatureSensor, protocol: io
[02/04/2019, 20:57:54] [Cozytouch] Unable to merge IO (16451345#2)
[02/04/2019, 20:57:54] [Cozytouch] Unable to merge IO (16451345#3)
[02/04/2019, 20:57:54] [Cozytouch] Unable to merge Etage
[02/04/2019, 20:57:54] [Cozytouch] Unable to merge IO (16451345#9)
[02/04/2019, 20:57:54] [Cozytouch] Unable to merge RdC
[02/04/2019, 20:57:54] [Cozytouch] Unable to merge IO (16451345#11)

**Comment by dubocr** [comment]
Supprime les exclusions dans ton fichier de config.

**Comment by dubocr** [comment]
Tu pourras ensuite remettre ce que tu veux exclure sauf HP_Actuator car il porte les zones.

**Comment by raffoul** [comment]
Merci ça fonctionne. Par contre je n’arrive toujours pas à faire de dérogation.

**Comment by dubocr** [comment]
On avance, voici de quoi déroger lorsque le PAC est en mode auto ou programmation
[HeatingSystem.zip](https://github.com/dubocr/homebridge-tahoma/files/3038390/HeatingSystem.zip)
Pour les T°, j'ai modifié quelque chose mais je ne suis pas sur de comprendre exactement le problème. Peux-tu préciser.

Merci.

**Comment by raffoul** [comment]
Merci je testerai ce soir.

Pour les températures, je te donne un exemple, ce sera plus simple :

1 - Je choisi la température dans homekit (17 ou 17,5 ou 18). Je ne peux pas choisi choisir dans homekit une température à 0,1 près. L'application ne le permet pas.
2) Une fois ma température choisie dans homekit, par exemple 17, j'obtiens dans les logs la température 17,2 et c'est cette température qui est envoyée comme consigne à ma PAC.
3) Quand je vais sur la PAC, la température de consigne est 17,2 et non celle indiquée dans home kit (17)

Est-ce plus claire ?
Ca n'est pas évident d'expliquer textuellement le problème.

**Comment by raffoul** [comment]
J’obtiens l’erreur suivante 
[04/04/2019, 20:18:58] [Cozytouch] [RdC] setDerogatedTargetTemperature +2 others Error 400 Managed action group is invalid : setDerogationTime() : Invalid value for command parameter p1 : expected integer value between 0 and 24 but got 3600 (UNSPECIFIED_ERROR)

**Comment by dubocr** [comment]
Peux-tu mettre à jour le plugin et réessayer stp. J'ai modifié pour passer en heures.

Merci.

**Comment by raffoul** [comment]
Parfait un grand merci pour la résolution de mon problème. 
Je termine juste par une proposition d’évolution pour la gestion de l’eau chaude. Dans WaterHeatingSystem, il y a une fonction boot. L’idée est d’ajouter un switch qui active ce mode boost. Ce mode permet de chauffer davantage l’eau pour que l’on puisse prendre plus de douche. Parfait quand il y a beaucoup de monde chez soi. Ça serait possible de l’intégrer à terme ? Merci

**Comment by dubocr** [comment]
Bonjour,

Pour l'ECS, j'ai travaillé sur la partie boost, tu peux essayer ce fichier que je n'ai pas encore pu tester :
[WaterHeatingSystem.zip](https://github.com/dubocr/homebridge-tahoma/files/3053279/WaterHeatingSystem.zip)

Tiens moi au courant.

**Comment by raffoul** [comment]
Bonjour
Le switch n’apparait pas malgré la mise à jour du fichier. Pas d’erreur dans les logs et pas d’exclude dans la conf. Une idée ?

**Comment by dubocr** [comment]
J'ai mis à jour le plugin, cela devrait être bon en faisant un `sudo npm update -g homebridge-tahoma`

**Comment by raffoul** [comment]
Yes merci ça fonctionne.

Cordialement,

Raphaël Limbach
Appt 23, 9 rue de la Fauvette 35230 Bourgbarré
+33 6 87 88 95 83
