### ISSUE TITLE
Alarm Protexiom

### ISSUE THREAD

**Issue by plusselmann** [dubocr/homebridge-tahoma#88]
![D8F0F4AB-CD02-40DE-98BE-8D398920B512](https://user-images.githubusercontent.com/49905504/56621121-8dca8f00-662b-11e9-81b6-3a08660d6609.jpeg)
![AE34934E-AB3E-4A1D-9053-ADC1EA36866C](https://user-images.githubusercontent.com/49905504/56621122-8dca8f00-662b-11e9-8c8c-1009753df2d0.jpeg)
![152EF6F2-E6B9-43A9-BA88-ADDA4021783D](https://user-images.githubusercontent.com/49905504/56621123-8e632580-662b-11e9-8caa-65bcc57f2c7d.jpeg)
![E34ACC76-E282-47FD-8827-AFF6E49BC596](https://user-images.githubusercontent.com/49905504/56621124-8e632580-662b-11e9-9972-208f0bf91e50.jpeg)

Bonjour,
Dans Tahoma, j'ai intégrer les Détecteurs de mouvement et ouvertures mais aussi mes sirènes et mon alarme.
Les detecters fonctionnent bien dans home kit.
Mais mon alarme est complètement ignorée.

Voici le message a l'initialisation.
[4/23/2019, 12:34:31 PM] [Tahoma] [Alarm] device type: Alarm, name: internal:TSKAlarmComponent, protocol: internal
[4/23/2019, 12:34:31 PM] [Tahoma] Device Alarm ignored
[4/23/2019, 12:34:31 PM] [Tahoma] [Exterieur] device type: Siren, name: rtd:OutdoorSirenRTDComponent, protocol: rtd
[4/23/2019, 12:34:31 PM] [Tahoma] Device type Siren unknown
[4/23/2019, 12:34:31 PM] [Tahoma] [Interieur] device type: Siren, name: rtd:IndoorSirenRTDComponent, protocol: rtd
[4/23/2019, 12:34:31 PM] [Tahoma] Device type Siren unknown

**Comment by plusselmann** [comment]
Avez vous besoin d’information complémentaire?
Est il possible d’avoir l’alarme intégrée à HomeKit ?

**Comment by dubocr** [comment]
Bonjour,

J'ai supprimé le masquage est device "internal" dans la dernière version. Pouvez-vous mettre à jour et me dire si cela fonctionne. D'habitude les alarmes sont représentées avec deux capteurs et l'internal n'est pas pris en compte. Cela risque de créer des doublons chez les autres utilisateurs. Quel est le modèle marque de l'alarme ?

Merci.

**Comment by plusselmann** [comment]
Bonjour,

J'ai une alarme Somfy Protexiom 600.

Les 2 Sirènes sont maintenant bien présentes et lorsque j'active le switch dans Homekit, elle fonctionnes. Parcontre lorsque j'essaye de mettre l'alarme en  route de puis HomeKit, home bridge crash avec les erreurs suivantes.
/usr/local/lib/node_modules/homebridge-tahoma/services/Alarm.js:75
                    commands.push(new Command('alarmOn'));
                             ^
TypeError: Cannot read property 'push' of null
    at Alarm.setState (/usr/local/lib/node_modules/homebridge-tahoma/services/Alarm.js:75:30)
    at Characteristic.SecuritySystemTargetState.emit (events.js:182:13)
    at Characteristic.SecuritySystemTargetState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at HAPServer.emit (events.js:182:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by dubocr** [comment]
Bonjour,

En attendant une mise à jour, tu peux corriger la ligne 46 par 
`var commands = [];`

**Comment by dubocr** [comment]
Normalement c'est mis à jour dans la dernière version.

**Comment by dubocr** [comment]
Bonjour,

Si vous mettez à jour le plugin il faudra ajouter la configuration suivante dans le fichier de config homebridge :
`"exclude": ["!internal"]`
