### ISSUE TITLE
this.updateReachability is not a function

### ISSUE THREAD

**Issue by lboue** [dubocr/homebridge-tahoma#92]
Bonjour,

J'ai fait un test avec un 'DHWP Actuator' sur ma box en lien avec le commit e286360d394e3d044d147974361af637d7b95b04.
Voici ce que cela donne avec la box éteinte avec donc une erreur de l'API lorsque je tente de changer de mode sur le thermostat :
```

[2019-5-6 20:12:00] [Connexoon] [DHWP Actuator] setBoostModeDuration[60]
[2019-5-6 20:12:01] [Connexoon] Error 400 Managed action group is invalid : No such command : setBoostModeDuration on device io://0808-0476-7160/7190495#1 (io:AtlanticDomesticHotWaterProductionIOComponent) (UNSPECIFIED_ERROR)
[2019-5-6 20:12:01] TypeError: this.updateReachability is not a function
    at OverkizDevice.<anonymous> (/tmp/homebridge-tahoma/overkiz-device.js:133:27)
    at /tmp/homebridge-tahoma/overkiz-api.js:351:17
    at Request.authCallback [as _callback] (/tmp/homebridge-tahoma/overkiz-api.js:214:17)
    at Request.self.callback (/tmp/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/tmp/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/tmp/homebridge-tahoma/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
[2019-5-6 20:12:01] Got SIGTERM, shutting down Homebridge...
```

Cdt
Ludovic

**Comment by lboue** [comment]
Par contre si je rebranche la box mais en ayant une erreur de groupe cela m'affiche bien une erreur dans HomeKit comme ci-dessous :


![IMG_2185](https://user-images.githubusercontent.com/938089/57252360-31646800-704c-11e9-9795-7b9c1c12e7d2.jpg)

Avec cela dans les logs:
```
[2019-5-6 22:06:15] [Tv Salon] webOS - TV state: On
[2019-5-6 22:06:16] [Connexoon] [DHWP Actuator] setCurrentOperatingMode["off"]
[2019-5-6 22:06:16] [Connexoon] Error 400 Managed action group is invalid : setCurrentOperatingMode() : Invalid value for command parameter p1 : expected object value but got off (UNSPECIFIED_ERROR)
[2019-5-6 22:06:16] [Connexoon] [DHWP Actuator] setCurrentOperatingMode Error 400 Managed action group is invalid : setCurrentOperatingMode() : Invalid value for command parameter p1 : expected object value but got off (UNSPECIFIED_ERROR)
[2019-5-6 22:06:16] [Connexoon] [DHWP Actuator] setCurrentOperatingMode["on"]
[2019-5-6 22:06:16] [Connexoon] Error 400 Managed action group is invalid : setCurrentOperatingMode() : Invalid value for command parameter p1 : expected object value but got on (UNSPECIFIED_ERROR)
[2019-5-6 22:06:16] [Connexoon] [DHWP Actuator] setCurrentOperatingMode Error 400 Managed action group is invalid : setCurrentOperatingMode() : Invalid value for command parameter p1 : expected object value but got on (UNSPECIFIED_ERROR)
```

Cdt 
Ludovic

**Comment by dubocr** [comment]
Corrigé dans le dernière version. A tester.

Merci pour ton retour.
