### ISSUE TITLE
Error: This callback function has already been called by someone else

### ISSUE THREAD

**Issue by Brklnbnc** [dubocr/homebridge-tahoma#94]
Since updating the plugin to the latest version i get this error message when controlling my velux roof windows by using the slider in Apple Home app.
Homebridge 0.4.49
Homebridge-TaHoma 0.2.0 (now reverted back to 0.1.51)

```
May  9 16:29:22 homebridge homebridge[3420]: [5/9/2019, 4:29:22 PM] [Tahoma] [Keuken Dakraam 2] setClosure[29]
May  9 16:29:24 homebridge homebridge[3420]: [5/9/2019, 4:29:24 PM] [Tahoma] [Keuken Dakraam 2] setClosure[11]
May  9 16:29:26 homebridge homebridge[3420]: [5/9/2019, 4:29:26 PM] [Tahoma] [Keuken Dakraam 2] setClosure CMDCANCELLED
**May  9 16:29:26 homebridge homebridge[3420]: [5/9/2019, 4:29:26 PM] Error: This callback function has already been called by someone else; it can only be called one time.**
May  9 16:29:26 homebridge homebridge[3420]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
May  9 16:29:26 homebridge homebridge[3420]:     at Window.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/services/WindowCovering.js:123:82)
May  9 16:29:26 homebridge homebridge[3420]:     at OverkizDevice.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/overkiz-device.js:137:17)
May  9 16:29:26 homebridge homebridge[3420]:     at pollingtoevent.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:109:21)
May  9 16:29:26 homebridge homebridge[3420]:     at pollingtoevent.emit (events.js:182:13)
May  9 16:29:26 homebridge homebridge[3420]:     at done (/usr/lib/node_modules/homebridge-tahoma/node_modules/polling-to-event/index.js:63:20)
May  9 16:29:26 homebridge homebridge[3420]:     at /usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:91:14
May  9 16:29:26 homebridge homebridge[3420]:     at Request.authCallback [as _callback] (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:216:17)
May  9 16:29:26 homebridge homebridge[3420]:     at Request.self.callback (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
May  9 16:29:26 homebridge homebridge[3420]:     at Request.emit (events.js:182:13)
May  9 16:29:26 homebridge homebridge[3420]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
May  9 16:29:26 homebridge homebridge[3420]:     at Request.emit (events.js:182:13)
May  9 16:29:26 homebridge homebridge[3420]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1083:12)
May  9 16:29:26 homebridge homebridge[3420]:     at Object.onceWrapper (events.js:273:13)
May  9 16:29:26 homebridge homebridge[3420]:     at IncomingMessage.emit (events.js:187:15)
May  9 16:29:26 homebridge homebridge[3420]:     at endReadableNT (_stream_readable.js:1094:12)
May  9 16:29:26 homebridge homebridge[3420]:     at process._tickCallback (internal/process/next_tick.js:63:19)
May  9 16:29:26 homebridge homebridge[3420]: [5/9/2019, 4:29:26 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by dubocr** [comment]
Bonjour,

Cela devrait être corrigé dans la dernière version.

Merci.
