### ISSUE TITLE
 TypeError: this.triggerCallback is not a function

### ISSUE THREAD

**Issue by Shana611** [dubocr/homebridge-tahoma#99]
I can't use any of Tahoma product on my home kit this error comes up

TypeError: this.triggerCallback is not a function
    at OverkizDevice.executeCommand (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-device.js:103:9)
    at GarageDoorOpener.setState (/usr/local/lib/node_modules/homebridge-tahoma/services/GarageDoorOpener.js:63:21)
    at emitMany (events.js:146:13)
    at Characteristic.TargetDoorState.emit (events.js:223:7)
    at Characteristic.TargetDoorState.Characteristic.setValue (/usr/local/lib/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at emitMany (events.js:146:13)
    at HAPServer.emit (events.js:223:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by dubocr** [comment]
Hi,

Thank you, this will be fixed in last release. But it'll still not works as it mean there is no command associated with this action. Could you please log at https://dev.duboc.pro/tools/setup and tell me what HomeKit action you try to execute and on which device.

Thanks

**Comment by Shana611** [comment]
raspberrypi homebridge[303]: [2019-5-29 09:16:06] [Tahoma] No target command for My Gate

**Comment by dubocr** [comment]
Thanks, it'll be fixed until 8pm.
